### ISSUE TITLE
status and state change requests not processing

### ISSUE THREAD

**Issue by brandoniske** [iRayanKhan/homebridge-chamberlain#53]
My opener's status and state change requests are not processing as of this afternoon, but had been working previously with no changes made. 

Not seeing any errors in homebridge status/log. Maybe API changes again?

**Comment by pb4ugoout** [comment]
I’m having the same problem. I may have to try a different plugin to see if I can regain access through homebridge

**Comment by tteuer** [comment]
Same issue. Started happened yesterday afternoon. No errors either but state change does not process.

**Comment by jpetticrew** [comment]
+1 for same issue. Seems like a change was made with the API.

**Comment by pb4ugoout** [comment]
The fix mentioned above resolved my problem.

**Comment by tteuer** [comment]
The fix above worked for me as well! Working like normal again. Thank you!

**Comment by iRayanKhan** [comment]
Closed, Fixed in latest release. 
Upgrade this plugin using
``` sudo npm I -g homebridge-chamberlain```
This now utilizes the V5 Api.

**Comment by jpetticrew** [comment]
1.0.5 did not fix this for me. Now I am getting “no response” from my garage door and HTTP 500 errors on the console multiple times per minute.

**Comment by iRayanKhan** [comment]
Can you print out the exact output? @jpetticrew

**Comment by smallen13** [comment]
@jpetticrew the device ID on my door changed. I had to delete it from my config and output the new IDs to figure out what to replace it with.

**Comment by seldridge1** [comment]
@iRayanKhan Having the same issue with the upgrade. Throwing the below output:

Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by jpetticrew** [comment]
@seldridge1 That was the exact error I was getting. I deleted the deviceID from my confit file and it started working. I think @smallen13 is right. I guess the deviceID changed, but I only have one door so I guess I didn’t actually need it.

**Comment by seldridge1** [comment]
@jpetticrew, thanks. @smallen13 is correct. All is well again. Thanks!

**Comment by smallen13** [comment]
I only have one door, but my opener has two device IDs. First one was the one that works. Second one didn’t do anything, and resulted in an error. Would love to know what it’s there for.

**Comment by seldridge1** [comment]
@smallen13, same set up. Second device ID worked for me, first threw an error.

**Comment by iRayanKhan** [comment]
I’ve heard about multiple ID’s being generated for one device, or multiple for each type of device. The reason is seems to be doing this, is either an api/server error, or your opener has another accessory like a light, mine does too, but only generated one ID. I’ll add this to the common issues page.

**Comment by russmo** [comment]
I had two ids of the form GW00000##### and CG##########.  The CG########## is the one that works for my door with myq.  The numbers after GW in the GW00000##### deviceid matches the serial number of my ethernet connected chamberlain internet gateway device if that is helpful.

**Comment by russmo** [comment]
Here is the JSON returned when I queried the MyQ V5 API with curl on the command line.  Pretty easy to pick off the "device_family": "gateway" / "device_type": "ethernetgateway" as compared to the  "device_family": "garagedoor" / "device_type": "garagedooropener".  Perhaps this plugin should be filtering out gateways since it configures a single accessory.

```
{
  "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices",
  "count": 2,
  "items": [
    {
      "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX",
      "serial_number": "GW00000XXXXX",
      "device_family": "gateway",
      "device_platform": "myq",
      "device_type": "ethernetgateway",
      "name": "My Hub",
      "created_date": "2018-03-26T01:14:25.807",
      "state": {
        "firmware_version": "4.2",
        "homekit_capable": false,
        "homekit_enabled": false,
        "learn": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX/learn",
        "learn_mode": false,
        "updated_date": "2019-10-22T05:18:16.5459703Z",
        "physical_devices": [],
        "pending_bootload_abandoned": false,
        "online": true,
        "last_status": "2019-10-22T05:18:16.5459703Z"
      }
    },
    {
      "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/CG0XXXXXXXXX",
      "serial_number": "CG0XXXXXXXXX",
      "device_family": "garagedoor",
      "device_platform": "myq",
      "device_type": "garagedooropener",
      "name": "Garage",
      "parent_device": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX",
      "parent_device_id": "GW00000XXXXX",
      "created_date": "2018-11-03T00:26:35.933",
      "state": {
        "gdo_lock_connected": false,
        "attached_work_light_error_present": false,
        "door_state": "closed",
        "open": "http://api.myqdevice.com/api/v5/accounts/XXXXX/devices/CG0XXXXXXXXX/open",
        "close": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/CG0XXXXXXXXX/close",
        "last_update": "2019-10-22T03:54:11.8069727Z",
        "passthrough_interval": "00:00:00",
        "door_ajar_interval": "00:00:00",
        "invalid_credential_window": "00:00:00",
        "invalid_shutout_period": "00:00:00",
        "is_unattended_open_allowed": true,
        "is_unattended_close_allowed": true,
        "aux_relay_delay": "00:00:00",
        "use_aux_relay": false,
        "aux_relay_behavior": "None",
        "rex_fires_door": false,
        "command_channel_report_status": false,
        "control_from_browser": false,
        "report_forced": false,
        "report_ajar": false,
        "max_invalid_attempts": 0,
        "online": true,
        "last_status": "2019-10-22T05:18:16.5459703Z"
      }
    }
  ]
}
```

**Comment by frahli** [comment]
I´m getting the two devices error, too

`[2019-10-22 4:28:51 PM] [Tor] Error: Multiple controllable devices found: GWXXXXXXXXXXXX, CGXXXXXXXX
    at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)`


 I fixed my config like this:

> 
{
            "accessory": "Chamberlain",
            "name": "Tor",
            "username": "mail@domain.com",
            "password": "passowrd",
            "deviceid": "CGXXXXXXXX"
}

But nothing happens. Can somebody help me?

**Comment by frahli** [comment]
> But nothing happens. Can somebody help me?

Got the solution: I had ro write: deviceId with a capital i

**Comment by iRayanKhan** [comment]
@russmo later tonight I'll hopefully have a branch for you to test to see if it filters out the gateway.

**Comment by russmo** [comment]
@iRayanKhan I can test in the evening or morning when you are ready.  The homebridge-myq2 (and homebridge-liftmaster2) plugins take a platform approach that handles mutliple devices versus the homebridge-chamberlain accessory approach that configures a single device per accessory in the config.json.  I only have one door and no other myq controlled devices, plus it seems like the PR from @ConradIrwin to use myq api v5 means this plugin has a good chance of working with myq for a longer time.  My goal is to set and forget everything and not mess with for 6-12 months until myq does something to block these third-party plugins again.

**Comment by iRayanKhan** [comment]
@russmo the last Api change before this one was August 6th, so they'll keep trying. 
I currently made [this branch](https://github.com/caseywebdev/homebridge-chamberlain/tree/v4Api) for those who have issues with the latest version. Read the top bit of the ReadMe for some info on it. As for the ethernet gateway fix, I have a solution and will make another branch to see if it works and for people to test, as I don't have a MyQ ethernet gateway.
Let me know if the fork works, or the latest version of this plugin.

**Comment by russmo** [comment]
@iRayanKhan understood.  To be clear release 1.0.5 works great for me when I specify the correct deviceId.  I will try your gateway filtering branch when it's ready and let you know if it works without specifying a deviceId in the config for someone with one garage door and an internet gateway.  I have the 828LM device ([https://www.liftmaster.com/828lm-internet-gateway/p/G828LM](https://www.liftmaster.com/828lm-internet-gateway/p/G828LM))

**Comment by iRayanKhan** [comment]
Thank you for all this info, especially:

>The numbers after GW in the GW00000##### deviceid matches the serial number of my ethernet connected chamberlain internet gateway device if that is helpful.
>
If anyone else has ethernet gateways with a serial number not starting with ```GW``` please let me know.

**Comment by iRayanKhan** [comment]
@russmo I'm going to close this issue, please make a new one about the gateways so that it's not mixed in with the API being broken talk.
Edit: Added Branch "```Test```"

**Comment by hawflakes** [comment]
How do I get the deviceId when the plugin is 500ing? Is there an easy/documented way to curl my way into this? Pardon my inexperience with node.js.

**Comment by iRayanKhan** [comment]
@hawflakes try the latest version of the plugin, then have the DeviceID field in the config blank, or the config file blank. Homebridge will then crash intentionally and say
[Chamberlain] (Device ID xx)

**Comment by hawflakes** [comment]
@iRayanKhan yes. I was hoping to see that but instead I see a whole lotta:
```
 Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Do I need to move aside the homebridge `accessories` and `persist` to let it think it's setting up for the first time to see these messages?

EDIT: forgot to say that I am running 1.0.5 (latest) and thanks for the help!

**Comment by iRayanKhan** [comment]
@hawflakes, any chance you are using docker?
I think clearing the accessories should work, if you want, it may be easier to do the following on a pi if use more than just this plugin.
```mkdir GarageBridge``` - New Directory
```cd GarageBridge``` - Change Directory path to this folder
``` nano config.json``` - Make a new config.json file with just this plugin in the config and device id's blank. Make sure to change the port, Mac address, and name.
```homebridge -U ~/GarageBridge/``` Runs homebridge for that specific path and watch the output show device ID's.

**Comment by hawflakes** [comment]
Sorry for the slow reply, @iRayanKhan I am using an RPi and following your instructions yielded me the codes! Now with the updated `deviceId` everything is working again.

**Comment by iRayanKhan** [comment]
Glad to hear it's all working! I'll add this as a fix in the common issues pages soon.
